# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1drnKsznLLWGyCmbxZtP_Y85UQIvkyT5y
"""

import streamlit as st
import pandas as pd
import numpy as np
import shap
import dice_ml
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
import matplotlib.pyplot as plt

# ==========================================
# 1. SETUP & MODEL TRAINING
# ==========================================
@st.cache_resource
def load_data_and_model():
    try:
        # Load dataset
        df = pd.read_csv("kidney_dataset.csv")
    except:
        # FALLBACK: Dummy Data so app doesn't crash if CSV is missing on server
        np.random.seed(42)
        data = {
            'Creatinine': np.random.uniform(0.5, 5.0, 100),
            'BUN': np.random.uniform(10, 50, 100),
            'Urine_Output': np.random.uniform(500, 3000, 100),
            'Age': np.random.randint(20, 90, 100),
            'Protein_in_Urine': np.random.uniform(0, 5, 100),
            'Water_Intake': np.random.uniform(1, 4, 100),
            'Diabetes': np.random.choice([0, 1], 100),
            'Hypertension': np.random.choice([0, 1], 100),
            'Medication': np.random.choice(['None', 'ACE', 'Diuretic'], 100),
            'CKD_Status': np.random.choice([0, 1], 100)
        }
        df = pd.DataFrame(data)

    target = "CKD_Status"
    cols_to_drop = [target]
    if "GFR" in df.columns: cols_to_drop.append("GFR")

    X = df.drop(columns=cols_to_drop, errors='ignore')
    y = df[target]

    numeric_cols = X.select_dtypes(include=['number']).columns
    categorical_cols = X.select_dtypes(include=['object']).columns

    preprocessor = ColumnTransformer([
        ('num', Pipeline([('imputer', SimpleImputer(strategy='median')), ('scaler', StandardScaler())]), numeric_cols),
        ('cat', Pipeline([('imputer', SimpleImputer(strategy='most_frequent')), ('onehot', OneHotEncoder(handle_unknown='ignore'))]), categorical_cols)
    ])

    model = Pipeline([
        ('preprocessor', preprocessor),
        ('classifier', RandomForestClassifier(n_estimators=50, random_state=42))
    ])

    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
    model.fit(X_train, y_train)

    return model, X_train, df

model_pipeline, X_train, df_full = load_data_and_model()

# ==========================================
# 2. EXPLANATION LOGIC
# ==========================================
def generate_shap_explanation(model, X_train, instance):
    try:
        preprocessor = model.named_steps['preprocessor']
        classifier = model.named_steps['classifier']

        # Transform inputs
        instance_trans = preprocessor.transform(instance)

        # SHAP Calculation
        explainer = shap.TreeExplainer(classifier)
        shap_values = explainer.shap_values(instance_trans)

        # Robust handling of SHAP output shapes
        if isinstance(shap_values, list):
            vals = shap_values[1] # Class 1 Risk
        else:
            vals = shap_values

        vals = np.array(vals).flatten()

        feature_names = (preprocessor.named_transformers_['num'].get_feature_names_out().tolist() +
                         preprocessor.named_transformers_['cat'].get_feature_names_out().tolist())

        # Trim to match lengths if necessary
        min_len = min(len(vals), len(feature_names))
        vals = vals[:min_len]
        feature_names = feature_names[:min_len]

        feature_importance = pd.DataFrame({'col_name': feature_names, 'feature_importance_vals': vals})
        feature_importance['abs_val'] = feature_importance['feature_importance_vals'].abs()
        feature_importance = feature_importance.sort_values(by='abs_val', ascending=False).head(3)

        text = "Based on the analysis, the **top 3 factors** driving this prediction are:\n"
        for _, row in feature_importance.iterrows():
            impact_type = "Increasing Risk 🔺" if row['feature_importance_vals'] > 0 else "Lowering Risk 🔻"
            text += f"- **{row['col_name']}**: {impact_type}\n"
        return text, feature_importance

    except Exception as e:
        return f"Could not generate SHAP graph. (Debug: {str(e)})", None

def generate_dice_counterfactual(model, df_full, instance):
    try:
        target = "CKD_Status"
        d = dice_ml.Data(dataframe=df_full, continuous_features=df_full.select_dtypes('number').columns.drop(target, errors='ignore').tolist(), outcome_name=target)
        m = dice_ml.Model(model=model, backend="sklearn")
        exp = dice_ml.Dice(d, m, method="random")

        e1 = exp.generate_counterfactuals(instance, total_CFs=1, desired_class=0)
        cf_df = e1.cf_examples_list[0].final_cfs_df
        return "To reduce risk, consider aiming for these values:", cf_df
    except Exception as e:
        return f"No simple changes found to reverse risk.", None

# ==========================================
# 3. UI LAYOUT
# ==========================================
st.set_page_config(layout="wide", page_title="Medical AI Assistant")

st.sidebar.header("📝 Patient Vitals")
st.sidebar.info("Adjust sliders to simulate patient data.")

# Inputs
creatinine = st.sidebar.slider('Creatinine', 0.0, 10.0, 1.2)
bun = st.sidebar.slider('BUN', 0.0, 100.0, 20.0)
urine = st.sidebar.slider('Urine Output', 0.0, 3000.0, 1500.0)
age = st.sidebar.slider('Age', 18, 90, 50)
protein = st.sidebar.slider('Protein in Urine', 0.0, 5.0, 0.0)
water = st.sidebar.slider('Water Intake', 0.0, 5.0, 2.0)
diab = st.sidebar.selectbox('Diabetes', [0, 1])
hyper = st.sidebar.selectbox('Hypertension', [0, 1])
meds = st.sidebar.selectbox('Medication', ['None', 'ACE', 'Diuretic'])

input_df = pd.DataFrame([{
    'Creatinine': creatinine, 'BUN': bun, 'Urine_Output': urine,
    'Diabetes': diab, 'Hypertension': hyper, 'Age': age,
    'Protein_in_Urine': protein, 'Water_Intake': water, 'Medication': meds
}])

# Main Area
col1, col2 = st.columns([1, 2])

with col1:
    st.subheader("Patient Profile")
    st.dataframe(input_df.astype(str).T, use_container_width=True)

with col2:
    st.subheader("Diagnostics")

    if st.button("Run Diagnostics", type="primary"):
        pred = model_pipeline.predict(input_df)[0]
        prob = model_pipeline.predict_proba(input_df)[0][1]

        st.session_state['pred'] = pred
        st.session_state['prob'] = prob
        st.session_state['run'] = True

    if st.session_state.get('run'):
        if st.session_state['pred'] == 1:
            st.error(f"⚠️ **High Risk** (Confidence: {st.session_state['prob']:.1%})")
        else:
            st.success(f"✅ **Low Risk**")

        st.divider()
        st.markdown("### 💬 AI Consultation")
        st.write("Examples: *'Why is the risk high?'* or *'How can I lower the risk?'*")

        user_q = st.text_input("Type your question here:")

        if user_q:
            q = user_q.lower()
            if any(x in q for x in ["why", "reason", "cause", "factor"]):
                st.markdown("#### 🔍 Root Cause (SHAP)")
                txt, sdf = generate_shap_explanation(model_pipeline, X_train, input_df)
                st.write(txt)
                if sdf is not None:
                    st.bar_chart(sdf.set_index('col_name')['feature_importance_vals'])

            elif any(x in q for x in ["change", "what if", "how to", "reduce"]):
                st.markdown("#### 🔮 Recommendation (DiCE)")
                txt, cdf = generate_dice_counterfactual(model_pipeline, df_full, input_df)
                st.write(txt)
                if cdf is not None:
                    st.dataframe(cdf)
            else:
                st.info("I didn't understand. Please ask about 'causes' or 'changes'.")